# Generated by Django 4.1.5 on 2023-01-15 16:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
