# Generated by Django 4.1.5 on 2023-01-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_alter_reply_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
    ]
