# Generated by Django 4.1.5 on 2023-01-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_alter_post_categories_alter_reply_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
